# https://pre-commit.com/hooks.html
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: local
    hooks:
      - id: check-version
        name: Check version
        entry: python misc/version.py check
        language: system
        always_run: true
        pass_filenames: false
      - id: update-requirements
        name: Update requirements.txt
        entry: pip-compile --output-file requirements.txt requirements.in
        language: system
        always_run: true
        pass_filenames: false
      - id: update-submodule
        name: Update submodule
        entry: git submodule update --remote
        language: system
        always_run: true
        pass_filenames: false
      - id: git-add-circuitpython
        name: Git add circuitpython
        entry: git add circuitpython
        language: system
        always_run: true
        pass_filenames: false
